name = "RiskSimulator"
uuid = "d80ce8e1-c758-40bc-a0e7-b6008fb95ad7"
authors = ["Robert Moss <mossr@cs.stanford.edu>"]
version = "0.1.0"

[deps]
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
