name = "STLCG"
uuid = "6ababdf7-4701-4f28-b3b2-5630f64e3c98"
desc = "A toolbox to compute the robustness of STL formulas using computation graphs"
authors = ["Karen Leung <karenl7@stanford.edu", "Nikos Arechiga <nikos.arechiga@tri.global", "Robert Moss <mossr@cs.stanford.edu>"]
version = "0.1.0"

[deps]
EllipsisNotation = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
